DROP TABLE COMPANY;

CREATE TABLE COMPANY(
	COMPANY_NAME VARCHAR2(100) CONSTRAINT COMPANY_COMPANY_NAME_PK PRIMARY KEY,
	USER_ID VARCHAR2(100) CONSTRAINT COMPANY_USER_ID
						  REFERENCES PAYMENT_USER(USER_ID),
	USER_NAME VARCHAR2(100)
);
SELECT * FROM COMPANY c ;