DROP TABLE PAYMENT_USER ;

CREATE TABLE PAYMENT_USER(
	USER_ID VARCHAR2(100) CONSTRAINT USER_USER_ID_PK PRIMARY KEY,
	USER_NAME VARCHAR2(100),
	JOIN_DATE DATE,
	PAYMENT_SEQ NUMBER CONSTRAINT USER_PAYMENT_SEQ_FK 
					   REFERENCES PAYMENT(PAYMENT_SEQ),
	PAYMENT_NAME VARCHAR2(100) 
);
SELECT * FROM PAYMENT_USER pu ;
