DROP TABLE PAYMENT ;

CREATE TABLE PAYMENT(
	PAYMENT_SEQ NUMBER CONSTRAINT PAYMENT_PAYMENT_SEQ_PK PRIMARY KEY,
	COMPANY_NAME VARCHAR2(100) ,					   
	COM_SIZE VARCHAR2(100),
	PAYMENT_NAME VARCHAR2(100),
	DATA VARCHAR2(100),
	VOICE VARCHAR2(100),
	TEXT VARCHAR2(100),
	COM_PRICE NUMBER,
	SER_ECT1 VARCHAR2(100)
);

CREATE SEQUENCE SEQ1
START WITH 0
INCREMENT BY 1
MINVALUE 0;

INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1) 
VALUES(SEQ1.NEXTVAL, 'LGU+', '5G', '유심 5G (5GB/기본)', '5GB', '무제한', '무재한', 14900, '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1) 
VALUES(SEQ1.NEXTVAL, 'LGU+', '5G', '5G 더빠른12G+', '5GB', '무제한', '무재한', 37900, '멜론');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1) 
VALUES(SEQ1.NEXTVAL, 'LGU+', '5G', '5G 스마트 12GB', '12GB', '무제한', '무재한', 25300, '멜론');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'LGU+', 'LTE', '아이즈11GB+', '11GB', '무제한 (부가통화량 : 300분)', '무제한', 14080, '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'LGU+', 'LTE', '데이터안심무제한7G+', '7GB', '무제한 (부가통화량 : 300분)', '무제한', 7700, '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'LGU+', 'LTE', '유심 통화마음껏 데이터 1.5GB', '1.5GB', '무제한 (부가통화량 : 50분)', '무제한', 7900, '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'LGU+', 'LTE', 'LTE 든든 무제한 11GB+(신)', '11GB', '무제한 (부가통화량 : 300분)', '무제한', 25900, '멜론');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'LGU+', 'LTE', '이야기 안심 7GB+', '7GB', '무제한 (부가통화량 : 300분)', '무제한', 12100, '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'LGU+', 'LTE', 'The 착한 데이터 유심 3.6GB', '3.6GB', '무제한 (부가통화량 : 50분)', '무제한', 10800, '');
--
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'SKT', '5G', '5G U모빙 9GB+', '9GB', '무재한(부가통화량 : 300분)', '무재한', 33060, '멜론');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'SKT', '5G', '5G 유심 ( 9GB+/통화맘껏)', '9GB', '무재한(부가통화량 : 300분)', '무재한', 38500, '멜론');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'SKT', '5G', '5G 이야기 무한 200GB', '200GB', '무재한(부가통화량 : 300분)', '무재한', 60800, '멜론');

INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'SKT', 'LTE', 'LTE 유심 (7GB+/ 통화맘껏)', '7GB', '무제한', '무재한', 17500, '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'SKT', 'LTE', 'U모빙 데이터 6.5GB', '6.5GB', '무재한(부가통화량 : 300분)', '무재한', 26200, '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'SKT', 'LTE', 'eSIM 완전마음껏', '11GB', '무재한(부가통화량 : 300분)', '무재한', 33000, '멜론');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'SKT', '3G', '뉴천사요금제', '900MB', '30분', '0건', 3900, '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'SKT', '3G', '우체국 (50분+30건)', '0GB', '50분', '30건', 2640, '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'SKT', '3G', '티플자녀4종 50% 기본료 할인(데이터 차단가능)', '0MB', '150분', '1000건', 4450, '');

INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'KT', '5G', '5G 10GB+', '10GB', '무제한 (부가통화량 : 300분)', '무제한', 21400, '지니뮤직');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'KT', '5G', '5G 통화 충분 5GB', '5GB', '무제한 (부가통화량 : 300분)', '무제한', 15300, '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'KT', '5G', 'WELL 5G 슬림', '8GB', '무제한 (부가통화량 : 300분)', '무제한', 37000, '지니뮤직');

INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'KT', 'LTE', 'USIM모빙데이터선택10G', '11GB', '무제한 (부가통화량 : 200분)', '무제한', 21010, '지니뮤직');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'KT', 'LTE', '모두다 맘껏 7.0GB+', '7GB', '음성량 : 무제한 (부가통화량 : 50분)', '무제한', 17500, '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'KT', 'LTE', '통화 맘껏 1.5GB', '1.5GB', '무제한 (부가통화량 : 30분)', '무제한', 7900, '');

INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'KT', 'LTE', '프리티든든한 10G', '10GB', '300분', '300건', 12100, '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'KT', 'LTE', '모두 충분 11GB+', '11GB', '무제한 (부가통화량 : 200분)', '무제한', 33000, '지니뮤직');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1)
VALUES(SEQ1.NEXTVAL, 'KT', 'LTE', '데이터안심300분15G+', '15GB', '음성량: 300분', '문자량: 300건', 23100, '지니뮤직');

SELECT * FROM PAYMENT p ;





