
DROP TABLE PAYMENT ;
DROP TABLE PAYMENT_USER ;
DROP TABLE COMPANY;
CREATE TABLE PAYMENT(
	PAYMENT_SEQ NUMBER CONSTRAINT PAYMENT_PAYMENT_SEQ_PK PRIMARY KEY,
	COMPANY_NAME VARCHAR2(100), --CONSTRAINT PAYMENT_COMPANY_NAME
							   --REFERENCES COMPANY(COMPANY_NAME),						   
	COM_SIZE VARCHAR2(100),
	PAYMENT_NAME VARCHAR2(100),
	DATA VARCHAR2(100),
	VOICE VARCHAR2(100),
	TEXT VARCHAR2(100),
	COM_PRICE NUMBER,
	SER_ECT1 VARCHAR2(100),
	SER_ECT2 VARCHAR2(100)
);

CREATE TABLE PAYMENT_USER(
	USER_ID VARCHAR2(100) CONSTRAINT USER_USER_ID_PK PRIMARY KEY,
	USER_NAME VARCHAR2(100),
	JOIN_DATE DATE,
	PAYMENT_SEQ NUMBER CONSTRAINT USER_PAYMENT_SEQ_FK 
					   REFERENCES PAYMENT(PAYMENT_SEQ),
	PAYMENT_NAME VARCHAR2(100) 
);

CREATE TABLE COMPANY(
	COMPANY_NAME VARCHAR2(100) CONSTRAINT COMPANY_COMPANY_NAME_PK PRIMARY KEY,
	USER_ID VARCHAR2(100) CONSTRAINT COMPANY_USER_ID
						  REFERENCES PAYMENT_USER(USER_ID),
	USER_NAME VARCHAR2(100)
);

SELECT * FROM PAYMENT;



SELECT * FROM PAYMENT_USER pu ;
SELECT * FROM COMPANY c ;

CREATE SEQUENCE SEQ1
START WITH 0
INCREMENT BY 1
MINVALUE 0;

INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1, SER_ECT2) -- LGU+
VALUES(SEQ1.NEXTVAL, 'LGU+', '5G', '유심 5G', '5GB', '200분', '100건', 10450, '', '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1, SER_ECT2)
VALUES(SEQ1.NEXTVAL, 'LGU+', 'LTE', '아이즈 15GB+', '15GB', '100분', '100건', 14080, '', '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1, SER_ECT2)
VALUES(SEQ1.NEXTVAL, 'LGU+', 'LTE', '유심 통화마음껏 데이터 6GB+', '11GB', '무재한(부가통화량 : 300분)', '무재한', 25900, '', '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1, SER_ECT2)
VALUES(SEQ1.NEXTVAL, 'SKT', '5G', '5G U모빙 9GB+', '9GB', '무재한(부가통화량 : 300분)', '무재한', 33060, '', '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1, SER_ECT2)
VALUES(SEQ1.NEXTVAL, 'SKT', 'LTE', 'LTE 유심 (11GB+/통화맘껏)', '11GB', '무재한(부가통화량 : 300분)', '무재한', 33990, '', '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1, SER_ECT2)
VALUES(SEQ1.NEXTVAL, 'SKT', '3G', '티플자녀4종 50% 기본료 할인(데이터 차단가능)', '0MB', '150분', '1000건', 4450, '', '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1, SER_ECT2)
VALUES(SEQ1.NEXTVAL, 'KT', '5G', '5G 200GB+', '200GB', '무제한 (부가통화량 : 300분)', '무제한', 37000, '', '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1, SER_ECT2)
VALUES(SEQ1.NEXTVAL, 'KT', 'LTE', '모두다 막힘없이 1GB+', '7GB', '무제한 (부가통화량 : 300분)', '무제한', 4950, '', '');
INSERT INTO PAYMENT
(PAYMENT_SEQ, COMPANY_NAME, COM_SIZE, PAYMENT_NAME, "DATA", VOICE, TEXT, COM_PRICE, SER_ECT1, SER_ECT2)
VALUES(SEQ1.NEXTVAL, 'KT', 'LTE', '모두다 맘껏 7.0GB+', '7GB', '무제한 (부가통화량 : 50분)', '무제한', 17500, '', '');






